name: poke_api
description: >
  Example of using fpdart to fetch pokemon from pokeapi with validation.
version: 2.0.0
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  fpdart:
    path: ../../packages/fpdart

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
