analyzer:
  exclude:
    - '**/*.g.dart'
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    unused_local_variable: ignore
    deprecated_field: ignore
