name: fpdart_effect
description: >
  Exploring an effect system implementation in dart
version: 0.0.1
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
author: Maglione Sandro <lass.maglio@gmail.com>
documentation: https://www.sandromaglione.com/course/fpdart-functional-programming-dart-and-flutter
issue_tracker: https://github.com/SandroMaglione/fpdart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
