name: fpdart_read_write_file
publish_to: none
version: 0.1.0
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
description: Example of Functional programming in Dart and Flutter using fpdart. Read and write local text file.
author: Maglione Sandro <lass.maglio@gmail.com>

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  fpdart:
    path: ../../.
  
dev_dependencies:
  lint: ^1.5.3