include: package:lints/recommended.yaml

linter:
  rules:
    annotate_overrides: true
    prefer_void_to_null: false

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
