name: file_read_stream
description: >
  Example of using fpdart to read an compute a large file using Stream.
version: 2.0.0
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  http: ^1.2.1
  equatable: ^2.0.5
  fpdart:
    path: ../../packages/fpdart

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
