name: fpdart_json_serializable
publish_to: none
version: 0.1.0
homepage: https://www.sandromaglione.com/
repository: https://github.com/SandroMaglione/fpdart
description: Example of using json_serializable with fpdart types.
author: Maglione Sandro <lass.maglio@gmail.com>

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  fpdart:
    path: ../../.
  json_serializable: ^5.0.0

dev_dependencies:
  build_runner: ^2.0.6
  json_annotation: ^4.1.0
  lint: ^1.5.3
  test: ^1.17.5
